[package]

name = "shitchat"
version = "0.0.1"
authors = ["Michael Wilson <wilsoniya@gmail.com>"]

[dependencies]
sha1 = "0.0.6" 

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize"
